services:
  rstudio:
    image: tclark89/tidyverse-extra
    ports: 
      - "8787:8787"
    environment:
      PASSWORD: rstudio
      ROOT: true
    volumes:
      - ~/.config/rstudio:/home/rstudio/.config/rstudio
      - ~/.local/share/rstudio:/home/rstudio/.local/share/rstudio
      - ~/code/R:/home/rstudio/workspace
