services:
  rstudio:
    image: tclark89/rstudio-extra:4.2.1
    ports: 
      - "8787:8787"
    environment:
      PASSWORD: rstudio
      ROOT: true
    volumes:
      - /home/tyler/.config/rstudio:/home/rstudio/.config/rstudio
      - /home/tyler/code/R:/home/rstudio/workspace
